# Generated by Django 2.0 on 2018-02-22 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Memes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='title', max_length=100, verbose_name='MEMeTitle')),
                ('image', models.CharField(default='memePic', max_length=100, verbose_name='memePic')),
                ('text1', models.CharField(default='funny', max_length=50, verbose_name='text1')),
                ('text2', models.CharField(default='funny', max_length=50, verbose_name='text2')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
